### ISSUE TITLE
还原PS中的投影到box-shaow属性

### ISSUE THREAD

**Issue by viajes7** [viajes7/blog#19]
![11](https://user-images.githubusercontent.com/35365161/49144128-8bdbf880-f337-11e8-8bd9-c7899a88e041.png)

### 1.问题
以前写CSS阴影效果的时候，感觉和设计稿总有出入，可能写的最多的就是：<code>box-shadow: 0 0 3px 5px #eee;</code>

但是页面上的效果总是不太理想，做不到百分百还原设计稿。

### 2.PS中的投影与box-shaow属性的对应关系
可以先看下这篇博客：[Photoshop投影与CSS中box-shadow的转换](http://www.mamicode.com/info-detail-1855541.html)

Photoshop中的投影设置如图所示：

![10](https://user-images.githubusercontent.com/35365161/49144150-95656080-f337-11e8-97e6-ce1e025b339a.png)

对于各项设置的解释：
- **混合模式**：Photoshop提供了各式各样的混合模式，但是CSS3阴影只支持正常模式（normal）。
- **颜色（color）**：阴影颜色。对应于CSS3阴影中的 color 值。
- **不透明度（opacity）**：阴影的不透明度。对应于CSS3阴影的颜色 rgba() 中的 a 值。
- **角度（Angle）**：投影的角度。
- **距离（Distance）**：阴影的距离。根据角度和距离可以换算出CSS3阴影中的x-offset和y-offet。 x-offset = Distance * cos(180 -Angle) ， y-offset = Distance * sin(180 - Angle)
- **扩展（Spread）**：阴影的扩展大小。控制阴影实体颜色和虚化颜色的多少。 Spread \* Size = 阴影中实体颜色的大小 。剩下的就是虚化的颜色。CSS3阴影 spread-radius = Spread * Size
- **大小（Size）**：阴影的大小。在CSS3中 blur-radius + spread-radius = Size 即 blur-radius = Size - spread-radius 。

### 3.LESS混合封装
根据上一步的对应关系，我们可以通过LESS封装一个函数，便于重复使用：

```less
// 转换PS阴影到box-shadow属性
// @rgba 颜色值
// @angle 角度
// @distance 距离
// @spread 范围
// @size 大小
// ---------------------------------------
.calc-box-shadow(@rgba, @angle, @distance, @spread, @size) {
    @x-offset: @distance * cos(180deg - @angle);
    @y-offset: @distance * sin(180deg - @angle);
    @blur: @size - @spread * @size;
    @spreadWidth: @spread * @size;
}
.box-shadow (@rgba, @angle, @distance, @spread, @size) {
    .calc-box-shadow(@rgba, @angle, @distance, @spread, @size);
    box-shadow: @x-offset @y-offset @blur @spreadWidth @rgba;
}
.box-shadow(@rgba, @angle, @distance, @spread, @size, @inset) {
    .calc-box-shadow(@rgba, @angle, @distance, @spread, @size);
    box-shadow: @x-offset @y-offset @blur @spreadWidth @rgba @inset;
}

// 使用示例
table thead tr {
    .box-shadow(rgba(0, 0, 0, .04), 90deg, 5px, 0, 5px, inset);
}
```

#### 单位
LESS的运算对于单位的识别还是很厉害的，可以如下这种书写，而不用自己拼接单位：
```less
@width: 100px;
@angle: 45deg;

p {
    width: @width + 2;
    height: 10px * cos(180deg - @angle)
}
```

#### 对于混合的识别
调用混合时，**函数名**以及**参数**需要一一对应，否则是无法识别的：
```less
.test(@param_1) {
    //...
}

// 使用的时候，需要传递参数个数不正确，也不会被识别
p {
    .test(1px, 2px);    // 不能识别到 .test
}
```

#### 变量作用域
有点类似于JavaScript的作用域查找把：
```less
@var: red;

#page {
  @var: white;
  #header {
    color: @var; // white
  }
}
```

参考我们封装的box-shadow混合class，可以发现，由于内阴影有最后一个参数<code>inset</code>，我们分开写了两个class，但是重复计算的变量，单独提为一个class，避免代码重复:
```less
.calc-box-shadow: {
    @x-offset: @distance * cos(180deg - @angle)
    //...
}
.box-shadow(@rgba, @angle, @distance, @spread, @size) {
    .calc-box-shadow();
    //...
}
.box-shadow(@rgba, @angle, @distance, @spread, @size, @inset) {
    .calc-box-shadow();
    //...
}
```

### 5.总结
嗯，前端说到底还是要界面写的好看呀，百分百还原设计稿，CSS简单易读，基本功还是不能丢的。
